import { FeeCategory, PlatformBaseFee } from './types';

export const PLATFORM_BASE_FEES: PlatformBaseFee[] = [
  {
    platform: 'shopee',
    transactionRate: 6,
    orderProcessingFee: 3000,
    effectiveFrom: '2026-05-01',
    sourceLabel: 'Shopee Vietnam seller fee policy',
    sourceUrl: 'https://help.shopee.vn/portal/4/article/77243',
  },
  {
    platform: 'tiktok',
    transactionRate: 6,
    orderProcessingFee: 3000,
    effectiveFrom: '2026-05-09',
    sourceLabel: 'TikTok Shop Vietnam seller fees',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=8858869405370113&lang=en',
  },
];

export const FEE_CATEGORIES: FeeCategory[] = [
  // Shopee: only categories with an exact current snapshot are enabled in V1.
  {
    id: 'shopee-baby-skincare',
    platform: 'shopee',
    group: 'Mẹ & Bé',
    label: 'Chăm sóc da cho bé',
    standardCommissionRate: 10.5,
    mallCommissionRate: 14,
    effectiveFrom: '2026-05-23',
    sourceStatus: 'reference-snapshot',
    sourceLabel: 'Shopee fee update 23/05/2026',
    sourceUrl: 'https://www.sapo.vn/blog/shopee-tang-phi-hang-loat-tu-23-05',
  },
  {
    id: 'shopee-baby-bath-shampoo',
    platform: 'shopee',
    group: 'Mẹ & Bé',
    label: 'Sản phẩm tắm & gội cho bé',
    standardCommissionRate: 10.5,
    mallCommissionRate: 14.7,
    effectiveFrom: '2026-05-23',
    sourceStatus: 'reference-snapshot',
    sourceLabel: 'Shopee fee update 23/05/2026',
    sourceUrl: 'https://www.sapo.vn/blog/shopee-tang-phi-hang-loat-tu-23-05',
  },
  {
    id: 'shopee-purified-water',
    platform: 'shopee',
    group: 'Thực phẩm & Đồ uống',
    label: 'Nước tinh khiết',
    standardCommissionRate: 10,
    mallCommissionRate: 13.7,
    effectiveFrom: '2026-05-23',
    sourceStatus: 'reference-snapshot',
    sourceLabel: 'Shopee fee update 23/05/2026',
    sourceUrl: 'https://www.sapo.vn/blog/shopee-tang-phi-hang-loat-tu-23-05',
  },
  {
    id: 'shopee-dried-food',
    platform: 'shopee',
    group: 'Thực phẩm & Đồ uống',
    label: 'Thực phẩm khô',
    standardCommissionRate: 10,
    mallCommissionRate: 13.7,
    effectiveFrom: '2026-05-23',
    sourceStatus: 'reference-snapshot',
    sourceLabel: 'Shopee fee update 23/05/2026',
    sourceUrl: 'https://www.sapo.vn/blog/shopee-tang-phi-hang-loat-tu-23-05',
  },
  {
    id: 'shopee-motorcycle',
    platform: 'shopee',
    group: 'Ô tô & Xe máy',
    label: 'Mô tô, xe máy',
    standardCommissionRate: 1.5,
    mallCommissionRate: 1.5,
    effectiveFrom: '2026-05-23',
    sourceStatus: 'reference-snapshot',
    sourceLabel: 'Shopee fee update 23/05/2026',
    sourceUrl: 'https://www.sapo.vn/blog/shopee-tang-phi-hang-loat-tu-23-05',
  },
  {
    id: 'shopee-car',
    platform: 'shopee',
    group: 'Ô tô & Xe máy',
    label: 'Ô tô',
    standardCommissionRate: 3.5,
    mallCommissionRate: 3.5,
    effectiveFrom: '2026-05-23',
    sourceStatus: 'reference-snapshot',
    sourceLabel: 'Shopee fee update 23/05/2026',
    sourceUrl: 'https://www.sapo.vn/blog/shopee-tang-phi-hang-loat-tu-23-05',
  },
  {
    id: 'shopee-laptop',
    platform: 'shopee',
    group: 'Máy tính & Laptop',
    label: 'Laptop',
    standardCommissionRate: 2,
    mallCommissionRate: 3.8,
    effectiveFrom: '2026-05-23',
    sourceStatus: 'reference-snapshot',
    sourceLabel: 'Shopee fee update 23/05/2026',
    sourceUrl: 'https://www.sapo.vn/blog/shopee-tang-phi-hang-loat-tu-23-05',
  },

  // TikTok Shop: exact Level-3 rates from the official July/August 2026 fee table.
  {
    id: 'tiktok-mobile-phone',
    platform: 'tiktok',
    group: 'Điện tử',
    label: 'Điện thoại di động',
    standardCommissionRate: 2,
    mallCommissionRate: 2.5,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
  {
    id: 'tiktok-laptop',
    platform: 'tiktok',
    group: 'Điện tử',
    label: 'Laptop',
    standardCommissionRate: 2,
    mallCommissionRate: 3.8,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
  {
    id: 'tiktok-keyboard-mouse',
    platform: 'tiktok',
    group: 'Điện tử',
    label: 'Bàn phím & Chuột',
    standardCommissionRate: 9.5,
    mallCommissionRate: 13.7,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
  {
    id: 'tiktok-phone-case',
    platform: 'tiktok',
    group: 'Điện tử',
    label: 'Ốp lưng / Kính cường lực / Sticker điện thoại',
    standardCommissionRate: 13.5,
    mallCommissionRate: 15.7,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
  {
    id: 'tiktok-power-bank',
    platform: 'tiktok',
    group: 'Điện tử',
    label: 'Sạc dự phòng',
    standardCommissionRate: 13.5,
    mallCommissionRate: 15.7,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
  {
    id: 'tiktok-tv',
    platform: 'tiktok',
    group: 'Điện gia dụng',
    label: 'Tivi',
    standardCommissionRate: 7.5,
    mallCommissionRate: 3.8,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
  {
    id: 'tiktok-air-purifier',
    platform: 'tiktok',
    group: 'Điện gia dụng',
    label: 'Máy lọc không khí',
    standardCommissionRate: 10,
    mallCommissionRate: 8.5,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
  {
    id: 'tiktok-womens-tshirt',
    platform: 'tiktok',
    group: 'Thời trang',
    label: 'Áo thun nữ',
    standardCommissionRate: 15,
    mallCommissionRate: 17.1,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
  {
    id: 'tiktok-mens-tshirt',
    platform: 'tiktok',
    group: 'Thời trang',
    label: 'Áo thun nam',
    standardCommissionRate: 15,
    mallCommissionRate: 17.1,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
  {
    id: 'tiktok-serum',
    platform: 'tiktok',
    group: 'Sắc đẹp',
    label: 'Serum & tinh chất dưỡng da',
    standardCommissionRate: 15.5,
    mallCommissionRate: 18.8,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
  {
    id: 'tiktok-instant-noodles',
    platform: 'tiktok',
    group: 'Thực phẩm & Đồ uống',
    label: 'Mì ăn liền',
    standardCommissionRate: 8.5,
    mallCommissionRate: 11.7,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
  {
    id: 'tiktok-small-pet-food',
    platform: 'tiktok',
    group: 'Thú cưng',
    label: 'Thức ăn thú cưng nhỏ',
    standardCommissionRate: 12.5,
    mallCommissionRate: 14.7,
    effectiveFrom: '2026-07-03',
    sourceStatus: 'official',
    sourceLabel: 'TikTok Shop Platform Commission Fee',
    sourceUrl: 'https://seller-vn.tiktok.com/university/essay?knowledge_id=3396736626312961&lang=en',
  },
];
